# -*- coding: utf-8 -*-
"""Translating_with_google_in_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7IgVgAZ7aqDCDfDAVP1Oqwj3K_H_THX
"""

!pip install googletrans==4.0.0-rc1

def translate(text, language='ru'):
    from googletrans import Translator

    # Создание экземпляра класса Translator
    translator = Translator()

    # Пример использования переводчика: translate('Это текст для перевода на английский', 'en')

    translated_text = translator.translate(text, dest=language)

    # Вывод переведенного текста
    print(translated_text.text)

    # 1. en — английский язык
    # 2. es — испанский язык
    # 3. fr — французский язык
    # 4. it — итальянский язык
    # 5. de — немецкий язык
    # 6. nl — нидерландский язык
    # 7. hu — венгерский язык
    # 8. pl — польский язык
    # 9. ru — русский язык
    # 10. ro — румынский язык
    # 11. sv — шведский язык
    # 12. tk — тамильский язык
    # 13. tr — турецкий язык
    # 14. zh — китайский язык (мандаринский и кантонский диалекты)
    # 15. ko — корейский язык
    # 16. el — испанский язык (США и Великобритания)
    # 17. ja — финский язык
    # 18. no — норвежский язык
    # 19. da — датский язык
    # 20. az — персидский язык